apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: flipza
  name: flipza
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/name: flipza
  type: LoadBalancer
